[build]
  functions = "./functions"

[[redirects]]
  from = "/_assets/*"
  to = "/_assets/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/entry-netlify"
  status = 200
  force = true